name: Buoy build
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest']
    steps:
      - name: Setup checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Create executable
        run: |
          python compiler.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Buoy-${{ matrix.os }}
          path: dist/*
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: Buoy-*
          merge-multiple: true
          path: dist
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.os }}
          release_name: Release ${{ matrix.os }}
          draft: false
          prerelease: false
      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/Buoy-*
          asset_name: Buoy-*
          asset_content_type: application/zip